FROM gcr.io/cloudsql-docker/gce-proxy:1.11

# make the 'app' folder the current working directory
WORKDIR /cloud-sql

EXPOSE 3306
RUN pwd
#RUN ./cloud-sql-proxy --credentials-file key.json ceri-m1-ecommerce-2022:europe-west1:mysql-primary



